(defun distance (x1 y1 z1 x2 y2 z2)
    (sqrt (+ (+ (expt (- x1 x2) 2) (expt (- y1 y2) 2)) (expt (- z1 z2) 2)))
)

(defun main()
    (setq x1 (read))
    (setq y1 (read))
    (setq z1 (read))
    (setq x2 (read))
    (setq y2 (read))
    (setq z2 (read))
    (write-line (write-to-string (distance x1 y1 z1 x2 y2 z2)))
)

(main)